[package]
name = "marketplace"
version = "1.0.0"
authors = []

[addresses] 
marketplace = "0xaa586426db3fbb1222f045f884054fa9b66b3b48758f0f8104b9c8b42193e209"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "main"
subdir = "aptos-framework"
